#include <iostream>
#include <string>
#include "embedded_data.h" // Generated by CMake

int main() {
    // Access the embedded HTML data
    const auto& html_data = embedded::index_html_data;
    size_t html_size = html_data.size(); // Get size from the array itself
    
    // Convert to string
    std::string html_content(reinterpret_cast<const char*>(html_data.data()), html_size);
    
    std::cout << "Embedded HTML content (" << html_size << " bytes):\n";
    std::cout << html_content << std::endl;
    
    return 0;
}